<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.1 (Python 3.9.4 on win32)" generated="20210428 14:11:28.942" rpa="false" schemaversion="2">
<suite id="s1" name="Owner" source="C:\users\user\pycharmprojects\spring-petclinic-angular\robotframework\tests\owner.robot">
<test id="s1-t1" name="user can add new owners and add pets">
<kw name="Open Browser">
<arg>about:blank</arg>
<arg>chrome</arg>
<msg timestamp="20210428 14:11:29.150" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20210428 14:11:29.150" endtime="20210428 14:11:29.150"/>
</kw>
<kw name="Go to">
<arg>http://localhost:4200/</arg>
<status status="NOT RUN" starttime="20210428 14:11:29.152" endtime="20210428 14:11:29.152"/>
</kw>
<doc>testar så att owner funktionen på pet clinic fungerar som det ska</doc>
<tag>test 1</tag>
<status status="FAIL" starttime="20210428 14:11:29.148" endtime="20210428 14:11:29.152">No keyword with name 'Open Browser' found.</status>
</test>
<doc>testing spring pet clinic angular</doc>
<status status="FAIL" starttime="20210428 14:11:28.959" endtime="20210428 14:11:29.154"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">test 1</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Owner">Owner</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210428 14:11:29.146" level="ERROR">Error in file 'C:\users\user\pycharmprojects\spring-petclinic-angular\robotframework\tests\owner.robot' on line 4: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\robot.exe
  c:\users\user\appdata\local\programs\python\python39\python39.zip
  c:\users\user\appdata\local\programs\python\python39\DLLs
  c:\users\user\appdata\local\programs\python\python39\lib
  c:\users\user\appdata\local\programs\python\python39
  c:\users\user\appdata\local\programs\python\python39\lib\site-packages</msg>
</errors>
</robot>
